In [2]:
import pandas as pd
ufo = pd.read_csv('http://bit.ly/uforeports')

In [3]:
ufo.columns

Index([u'City', u'Colors Reported', u'Shape Reported', u'State', u'Time'], dtype='object')

In [4]:
ufo = pd.read_csv('http://bit.ly/uforeports', usecols=['City', 'Time'])

In [6]:
ufo.columns

Index([u'City', u'Time'], dtype='object')

In [7]:
ufo = pd.read_csv('http://bit.ly/uforeports', nrows=3)

In [8]:
ufo

          City  Colors Reported Shape Reported State             Time
0       Ithaca              NaN       TRIANGLE    NY   6/1/1930 22:00
1  Willingboro              NaN          OTHER    NJ  6/30/1930 20:00
2      Holyoke              NaN           OVAL    CO  2/15/1931 14:00

In [9]:
for c in ufo.City:
    print c

Ithaca
Willingboro
Holyoke

In [10]:
for index, row in ufo.iterrows():
    print index, row.City, row.State

0 Ithaca NY
1 Willingboro NJ
2 Holyoke CO

In [11]:
drinks = pd.read_csv('http://bit.ly/drinksbycountry')

In [12]:
drinks.dtypes

country                          object
beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object

In [13]:
# select only numerice columns
import numpy as np
drinks.select_dtypes(include=[np.number])

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,0,0,0,0.0
1,89,132,54,4.9
2,25,0,14,0.7
3,245,138,312,12.4
4,217,57,45,5.9
5,102,128,45,4.9
6,193,25,221,8.3
7,21,179,11,3.8
8,261,72,212,10.4
9,279,75,191,9.7
10,21,46,5,1.3
11,122,176,51,6.3
12,42,63,7,2.0
13,0,0,0,0.0
14,143,173,36,6.3
15,142,373,42,14.4
16,295,84,212,10.5
17,263,114,8,6.8
18,34,4,13,1.1
19,23,0,0,0.4
20,167,41,8,3.8
21,76,173,8,4.6
22,173,35,35,5.4
23,245,145,16,7.2
24,31,2,1,0.6
25,231,252,94,10.3
26,25,7,7,4.3
27,88,0,0,6.3
28,37,1,7,4.0
29,144,56,16,4.0
...,...,...,...,...
163,128,178,7,5.6
164,90,2,2,4.7
165,152,60,186,7.2
166,185,100,280,10.2
167,5,35,16,1.0
168,2,15,0,0.3
169,99,258,1,6.4
170,106,27,86,3.9
171,1,1,4,0.1
172,36,2,19,1.3
173,36,21,5,1.1
174,197,156,7,6.4
175,51,3,20,1.3
176,51,22,7,1.4
177,19,71,32,2.2
178,6,41,9,1.0
179,45,9,0,8.3
180,206,237,45,8.9
181,16,135,5,2.8
182,219,126,195,10.4
183,36,6,1,5.7
184,249,158,84,8.7
185,115,35,220,6.6
186,25,101,8,2.4
187,21,18,11,0.9
188,333,100,3,7.7
189,111,2,1,2.0
190,6,0,0,0.1
191,32,19,4,2.5
192,64,18,4,4.7